# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O:\studioTools\maya\python\tool\setDress\assemblyBuilder\ui.ui'
#
# Created: Tue Jan 19 13:43:27 2016
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from qtshim import QtCore, QtGui
from qtshim import Signal
from qtshim import wrapinstance


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_assemblyBuilderUI(object):
    def setupUi(self, assemblyBuilderUI):
        assemblyBuilderUI.setObjectName(_fromUtf8("assemblyBuilderUI"))
        assemblyBuilderUI.resize(775, 578)
        self.centralwidget = QtGui.QWidget(assemblyBuilderUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.projectComboBox = QtGui.QComboBox(self.centralwidget)
        self.projectComboBox.setObjectName(_fromUtf8("projectComboBox"))
        self.horizontalLayout.addWidget(self.projectComboBox)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.typeComboBox = QtGui.QComboBox(self.centralwidget)
        self.typeComboBox.setObjectName(_fromUtf8("typeComboBox"))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.typeComboBox)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.subtypeComboBox = QtGui.QComboBox(self.centralwidget)
        self.subtypeComboBox.setObjectName(_fromUtf8("subtypeComboBox"))
        self.horizontalLayout.addWidget(self.subtypeComboBox)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout.setStretch(5, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.searchLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.searchLineEdit.setObjectName(_fromUtf8("searchLineEdit"))
        self.horizontalLayout_4.addWidget(self.searchLineEdit)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.viewComboBox = QtGui.QComboBox(self.centralwidget)
        self.viewComboBox.setObjectName(_fromUtf8("viewComboBox"))
        self.viewComboBox.addItem(_fromUtf8(""))
        self.viewComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.viewComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.assetListWidget = QtGui.QListWidget(self.centralwidget)
        self.assetListWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.assetListWidget.setProperty("showDropIndicator", False)
        self.assetListWidget.setDragEnabled(False)
        self.assetListWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.assetListWidget.setIconSize(QtCore.QSize(80, 80))
        self.assetListWidget.setViewMode(QtGui.QListView.IconMode)
        self.assetListWidget.setObjectName(_fromUtf8("assetListWidget"))
        self.verticalLayout_2.addWidget(self.assetListWidget)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_2.addWidget(self.line_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tipPlainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.tipPlainTextEdit.setEnabled(True)
        self.tipPlainTextEdit.setReadOnly(True)
        self.tipPlainTextEdit.setObjectName(_fromUtf8("tipPlainTextEdit"))
        self.horizontalLayout_5.addWidget(self.tipPlainTextEdit)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_5.addWidget(self.line_5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.numCreateLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.numCreateLineEdit.setObjectName(_fromUtf8("numCreateLineEdit"))
        self.horizontalLayout_2.addWidget(self.numCreateLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.seperateCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.seperateCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seperateCheckBox.setChecked(True)
        self.seperateCheckBox.setObjectName(_fromUtf8("seperateCheckBox"))
        self.verticalLayout.addWidget(self.seperateCheckBox)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.txLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.txLineEdit.setObjectName(_fromUtf8("txLineEdit"))
        self.horizontalLayout_6.addWidget(self.txLineEdit)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.tzLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.tzLineEdit.setObjectName(_fromUtf8("tzLineEdit"))
        self.horizontalLayout_6.addWidget(self.tzLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.addPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPushButton.sizePolicy().hasHeightForWidth())
        self.addPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addPushButton.setFont(font)
        self.addPushButton.setObjectName(_fromUtf8("addPushButton"))
        self.horizontalLayout_5.addWidget(self.addPushButton)
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(2, 2)
        self.horizontalLayout_5.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.setStretch(3, 13)
        self.verticalLayout_2.setStretch(5, 2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.countLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.countLineEdit.setObjectName(_fromUtf8("countLineEdit"))
        self.horizontalLayout_10.addWidget(self.countLineEdit)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.refreshPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshPushButton.sizePolicy().hasHeightForWidth())
        self.refreshPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.refreshPushButton.setFont(font)
        self.refreshPushButton.setObjectName(_fromUtf8("refreshPushButton"))
        self.horizontalLayout_9.addWidget(self.refreshPushButton)
        self.horizontalLayout_9.setStretch(0, 2)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.arListWidget = QtGui.QListWidget(self.centralwidget)
        self.arListWidget.setIconSize(QtCore.QSize(40, 40))
        self.arListWidget.setObjectName(_fromUtf8("arListWidget"))
        self.verticalLayout_3.addWidget(self.arListWidget)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.nameRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.nameRadioButton.setObjectName(_fromUtf8("nameRadioButton"))
        self.horizontalLayout_8.addWidget(self.nameRadioButton)
        self.nameLineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLineEdit.sizePolicy().hasHeightForWidth())
        self.nameLineEdit.setSizePolicy(sizePolicy)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.horizontalLayout_8.addWidget(self.nameLineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.selectRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.selectRadioButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectRadioButton.setChecked(True)
        self.selectRadioButton.setObjectName(_fromUtf8("selectRadioButton"))
        self.verticalLayout_5.addWidget(self.selectRadioButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.replacePushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replacePushButton.sizePolicy().hasHeightForWidth())
        self.replacePushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.replacePushButton.setFont(font)
        self.replacePushButton.setObjectName(_fromUtf8("replacePushButton"))
        self.horizontalLayout_7.addWidget(self.replacePushButton)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.setStretch(1, 6)
        self.verticalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_3)
        assemblyBuilderUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(assemblyBuilderUI)
        QtCore.QMetaObject.connectSlotsByName(assemblyBuilderUI)

    def retranslateUi(self, assemblyBuilderUI):
        assemblyBuilderUI.setWindowTitle(QtGui.QApplication.translate("assemblyBuilderUI", "Assembly Builder", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("assemblyBuilderUI", "Project :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("assemblyBuilderUI", "Type :", None, QtGui.QApplication.UnicodeUTF8))
        self.typeComboBox.setItemText(0, QtGui.QApplication.translate("assemblyBuilderUI", "prop", None, QtGui.QApplication.UnicodeUTF8))
        self.typeComboBox.setItemText(1, QtGui.QApplication.translate("assemblyBuilderUI", "setdress", None, QtGui.QApplication.UnicodeUTF8))
        self.typeComboBox.setItemText(2, QtGui.QApplication.translate("assemblyBuilderUI", "set", None, QtGui.QApplication.UnicodeUTF8))
        self.typeComboBox.setItemText(3, QtGui.QApplication.translate("assemblyBuilderUI", "vehicle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("assemblyBuilderUI", "Subtype :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("assemblyBuilderUI", "Search :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("assemblyBuilderUI", "View Mode :", None, QtGui.QApplication.UnicodeUTF8))
        self.viewComboBox.setItemText(0, QtGui.QApplication.translate("assemblyBuilderUI", "Icon", None, QtGui.QApplication.UnicodeUTF8))
        self.viewComboBox.setItemText(1, QtGui.QApplication.translate("assemblyBuilderUI", "List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("assemblyBuilderUI", "Number :", None, QtGui.QApplication.UnicodeUTF8))
        self.numCreateLineEdit.setText(QtGui.QApplication.translate("assemblyBuilderUI", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.seperateCheckBox.setText(QtGui.QApplication.translate("assemblyBuilderUI", "Seperate Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("assemblyBuilderUI", "TX :", None, QtGui.QApplication.UnicodeUTF8))
        self.txLineEdit.setText(QtGui.QApplication.translate("assemblyBuilderUI", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("assemblyBuilderUI", "TZ :", None, QtGui.QApplication.UnicodeUTF8))
        self.tzLineEdit.setText(QtGui.QApplication.translate("assemblyBuilderUI", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.addPushButton.setText(QtGui.QApplication.translate("assemblyBuilderUI", "ADD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("assemblyBuilderUI", "Asset Count :", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshPushButton.setText(QtGui.QApplication.translate("assemblyBuilderUI", "REFRESH", None, QtGui.QApplication.UnicodeUTF8))
        self.nameRadioButton.setText(QtGui.QApplication.translate("assemblyBuilderUI", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.selectRadioButton.setText(QtGui.QApplication.translate("assemblyBuilderUI", "Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.replacePushButton.setText(QtGui.QApplication.translate("assemblyBuilderUI", "REPLACE", None, QtGui.QApplication.UnicodeUTF8))

